### ISSUE TITLE
no readme??

### ISSUE THREAD

**Issue by Hero-Xero** [ToYoNiX/number-guessing-game#1]
what kind of professional doesn't have a **readme**? you expect me to navigate through this on my own? without even trying to describe your work. what does number guessing mean? does it mean I guess the number and you correct me? or do you guess and I correct you? it's confusing to say the least.

**Comment by ToYoNiX** [comment]
yeh, I know it's a little confusing. The game idea is it will always guess
your number under 30 times. I need to add a div for it or even a new page
but it's a lackluster game to say the least so it doesn't matter for me.
Edit: I will eventually add a readme and improve it even further but it's not on my priorities list right now.
